name: Create docker image

on:
  push:
    branches:
      - "feature_regressiontests"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Set up Docker Buildx
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/ppteamrepo:latest

      -
        name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          file: docker/Dockerfile
          tags: ${{ vars.DOCKERHUB_USERNAME }}/regressiontester:latest
      
      -
        name: Push image to GHCR
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ vars.DOCKERHUB_USERNAME }}/regressiontester:latest \
            ${{ vars.DOCKERHUB_USERNAME }}/regressiontester:latest
